apiVersion: apps/v1
kind: Deployment
metadata:
  name: inlets-client
  namespace: inlets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inlets-client
  template:
    metadata:
      labels:
        app: inlets-client
    spec:
      containers:
      - name: inlets-client
        image: inlets/inlets-pro:0.8.3
        imagePullPolicy: IfNotPresent
        command: ["inlets-pro"]
        args:
        - "tcp"
        - "client"
        - "--url=wss://192.168.86.50:8123/connect"
        - "--upstream=kubernetes.default.svc"
        - "--port=443"
        - "--token=<your auth token>"
        - "--license=<your inlets license>"
