apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: northstarweb-net
  namespace: default
spec:
  secretName: northstarweb-net-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: northstarweb.net
  dnsNames:
  - northstarweb.net
