apiVersion: v1
kind: Service
metadata:
  name: budgeto-client-lb 
spec:
  selector:
    app: budgeto-client
  ports:
    - name: server
      protocol: TCP
      port: 3000 
      targetPort: 3000 
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.86.239 
