apiVersion: v1
kind: Service
metadata:
  name: northstarclientlb 
spec:
  selector:
    app: northstar-client 
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80 
  clusterIP: 10.43.0.69 
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.86.240 
