apiVersion: v1
kind: Service
metadata:
  name: northstarclientlb 
spec:
  selector:
    app: northstar-client 
  ports:
    - name: client
      protocol: TCP
      port: 8080 
      targetPort: 80 
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.86.240 
