apiVersion: v1
kind: Service
metadata:
  name: chorewall
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "chorewall"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "3"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: chorewall
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000